server:
  address: 127.0.0.1
  port: 8082
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: localhost
    username: hmdp
    password: 123456
    virtual-host: /hmdp
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
#        关闭拒绝重新入队，而是进入私信队列
        default-requeue-rejected: false
#        关闭SpringBoot的重试机制，自己控制失败逻辑
        retry:
          enabled: false
#          开启手动确认模式
        acknowledge-mode: manual
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 5000ms
        multiplier: 1
mybatis-plus:
  type-aliases-package: com.dianping.entity # 别名扫描包
logging:
  level:
    com.dianping: debug
  pattern:
    dateformat: mm:ss.SSS